
public class Task
{
  protected string title;
  protected string desc;

  protected Interval time;

  protected int priority;

  public string GetTitle() => title;
  public Interval GetTime() => time;

  public void SetNewTime(Interval time) => this.time=time;
  //TODO other setters and getters...

  public Interval? Intersect(Task other){
    return time.Intersect(other.time);
  }

  public virtual List<Interval> UsedTime(Interval period){
    Interval? i = time.Intersect(period);
    List<Interval> R = new List<Interval>();
    if(i!=null){
      i.SetRefferedTask(this);
      R.Add(i);
    }
    return R;
  }


  public Task(){
    this.title = "New Task";
    this.desc = "Generic Task Generated By An Empty Constructor";
    this.time = new Interval();
    this.priority = 1;
  }

  public Task(string title, string desc, Interval time, int priority = 1){
    this.title = title;
    this.desc = desc;
    this.time = time;
    this.priority = priority;
  }

  public override string ToString()
  {
    return title + " " + desc;
  }
}

public class Routine : Task
{
  protected bool[] repeatDays;

  public Routine(){
    this.title = "New Routine";
    this.desc = "Generic Routine Generated By An Empty Constructor";
    this.time = new Interval();
    repeatDays = new bool[7];
  }

  public Routine(string title, string desc, Interval time, bool[] repeatDays){
    this.title = title;
    this.desc = desc;
    this.time = time;
    this.repeatDays = repeatDays;
  }

  //TODO IMPLEMENT MORE...
}

public class AdvancedRoutine : Routine{
  protected int repeatWeeks; //Every 2nd, every 3rd week etc.
  protected int weekOffset; // between 0 and (repeatWeeks-1)

  public AdvancedRoutine(){
    this.title = "New AdvancedRoutine";
    this.desc = "Generic AdvancedRoutine Generated By An Empty Constructor";
    this.time = new Interval();
    this.repeatDays = new bool[7];
    this.repeatWeeks = 2;
    this.weekOffset = 0;
  }

  public AdvancedRoutine(string title, string desc, Interval time, bool[] repeatDays, int repeatWeeks, int weekOffset){
    this.title = title;
    this.desc = desc;
    this.time = time;
    this.repeatDays = repeatDays;
    this.repeatWeeks = repeatWeeks;
    this.weekOffset = weekOffset;
  }

  //TODO IMPLEMENT MORE...
}